name: Build Android APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Unzip Project
        run: unzip -o myapp.zip

      - name: Grant Execute Permission
        run: |
          if [ -d "myapp" ]; then
            chmod +x myapp/android/gradlew
          else
            chmod +x android/gradlew
          fi

      - name: Build with Gradle
        run: |
          if [ -d "myapp" ]; then
            cd myapp/android
          else
            cd android
          fi
          echo "tasks.withType(com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction).configureEach { it.enabled = false }" >> app/build.gradle
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-android-app
          path: |
            myapp/android/app/build/outputs/apk/debug/app-debug.apk
            android/app/build/outputs/apk/debug/app-debug.apk
            
